Send the thumbnail update messages separately
Now that the thumbnail creation is fixed to create 300x300 instead of 100x100
images we're hitting the Kafka message size limits:

Traceback (most recent call last):
  File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-beta/conda_env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-beta/conda_env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-beta/conda_env/lib/python3.10/site-packages/damnit/backend/extract_data.py", line 389, in <module>
    Extractor().extract_and_ingest(args.proposal, args.run,
  File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-beta/conda_env/lib/python3.10/site-packages/damnit/backend/extract_data.py", line 273, in extract_and_ingest
    self.kafka_prd.send(self.db.kafka_topic, update_msg).get(timeout=30)
  File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-beta/conda_env/lib/python3.10/site-packages/kafka/producer/future.py", line 65, in get
    raise self.exception # pylint: disable-msg=raising-bad-type
  File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-beta/conda_env/lib/python3.10/site-packages/kafka/producer/kafka.py", line 596, in send
    self._ensure_valid_record_size(message_size)
  File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-beta/conda_env/lib/python3.10/site-packages/kafka/producer/kafka.py", line 654, in _ensure_valid_record_size
    raise Errors.MessageSizeTooLargeError(
kafka.errors.MessageSizeTooLargeError: [Error 10] MessageSizeTooLargeError: The message is 1120256 bytes when serialized which is larger than the maximum request size you have configured with the max_request_size configuration

Sending the updates for thumbnail variables separately fixes that, though it does
create more updates for the GUI which slows it down a bit. We perhaps should
refactor this to only send updated variable names and get the GUI to read the
updated values from the database.